# Generated by Django 4.2 on 2026-05-19 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('saas', 'SaaS'), ('physical', 'Physical Product'), ('event_pass', 'Event Pass'), ('experience', 'Experience'), ('merchandise', 'Merchandise'), ('course', 'Course'), ('gift_card', 'Gift Card')], max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('AED', 'UAE Dirham'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('content_ask', models.JSONField(default=dict)),
                ('kpi_preferences', models.JSONField(default=dict)),
                ('rights_tier', models.CharField(choices=[('none', 'None'), ('standard', 'Standard'), ('extended', 'Extended'), ('buyout', 'Buyout')], default='none', max_length=10)),
                ('raw_files_required', models.BooleanField(default=False)),
                ('exclusivity', models.CharField(choices=[('none', 'None'), ('category_30', 'Category 30 Days'), ('full_60', 'Full 60 Days')], default='none', max_length=15)),
                ('images', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('proposal_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_proposals', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
