services:
  - type: web
    name: barter-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn barter.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: barter.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
