# Generated by Django 4.2 on 2026-05-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('deals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcounter',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='counter_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countered_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_link', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='offers.offer'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('offer', 'creator')},
        ),
    ]
