# Generated by Django 4.2 on 2026-05-19 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('pro_active', models.BooleanField(default=False)),
                ('pro_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.CharField(default='nano', max_length=10)),
                ('tasks_this_period', models.JSONField(default=dict)),
                ('period_reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creator_memberships',
            },
        ),
        migrations.CreateModel(
            name='MembershipTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_logo_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('open', 'Open')], default='open', max_length=15)),
                ('points_value', models.PositiveIntegerField()),
                ('brief_richtext', models.TextField()),
                ('required_tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('available_to_tiers', models.JSONField(default=list)),
                ('available_to_markets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'membership_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_url', models.URLField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit_requested', 'Resubmit Requested')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membership_task_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
