# Generated by Django 4.2 on 2026-05-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatormembership',
            name='pending_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatormembership',
            name='points_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='membershiptask',
            name='available_again_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptask',
            name='brief',
            field=models.JSONField(default=dict),
        ),
    ]
