# Generated by Django 4.2 on 2026-05-19 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropsApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drops_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='DropsCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('awareness', 'Brand Awareness'), ('launch', 'Product Launch'), ('event_hype', 'Event Hype'), ('review', 'Product Review')], max_length=15)),
                ('total_slots', models.PositiveIntegerField()),
                ('filled_slots', models.PositiveIntegerField(default=0)),
                ('approval_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drops_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
