# Generated by Django 4.2 on 2026-05-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drops', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropscampaign',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dropscampaign',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops_campaign', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='dropsapplication',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='drops.dropscampaign'),
        ),
        migrations.AddField(
            model_name='dropsapplication',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dropsapplication',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.deal'),
        ),
        migrations.AlterUniqueTogether(
            name='dropsapplication',
            unique_together={('campaign', 'creator')},
        ),
    ]
