# Generated by Django 4.2 on 2026-05-19 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_terms', models.JSONField(default=dict)),
                ('rights_tier', models.CharField(max_length=20)),
                ('raw_files_required', models.BooleanField(default=False)),
                ('exclusivity', models.CharField(max_length=20)),
                ('deal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending_membership', 'Pending Membership'), ('active', 'Active'), ('delivered', 'Delivered'), ('revision_requested', 'Revision Requested'), ('complete', 'Complete'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending_membership', max_length=20)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('contract_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('attachment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deal_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('files', models.JSONField(default=list)),
                ('post_urls', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revision', 'Revision'), ('disputed', 'Disputed')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=300)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='deals.deal')),
            ],
            options={
                'db_table': 'revision_requests',
                'ordering': ['created_at'],
            },
        ),
    ]
