# Generated by Django 4.2 on 2026-05-19 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('proposal_received', 'Proposal Received'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_countered', 'Proposal Countered'), ('proposal_declined', 'Proposal Declined'), ('deal_room_created', 'Deal Room Created'), ('brand_shipped', 'Brand Shipped'), ('creator_confirmed', 'Creator Confirmed'), ('content_delivered', 'Content Delivered'), ('revision_requested', 'Revision Requested'), ('deal_complete', 'Deal Complete'), ('rating_received', 'Rating Received'), ('membership_submitted', 'Membership Submitted'), ('membership_approved', 'Membership Approved'), ('membership_rejected', 'Membership Rejected'), ('pro_expiring', 'Pro Expiring'), ('drops_application', 'Drops Application'), ('drops_approved', 'Drops Approved'), ('deal_message', 'Deal Message'), ('deal_disputed', 'Deal Disputed')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('deep_link', models.URLField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
